### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by NVasse** [doctrine/instantiator#31]
Hello, I wasn't sure if I had to post this here or on doctrine/orm :
``doctrine/orm 2.5.x-dev requires doctrine/instantiator ~1.0.1 -> no matching package found. ``

**Comment by mikeSimonson** [comment]
The package doctrine/instantiator 1.0.1 -> 1.0.5 exists so the problem is probably somewhere else in your requirements.

**Comment by mikeSimonson** [comment]
What did you do to get that error message ?

**Comment by Ocramius** [comment]
>  no matching package found.

Please put the complete error messages - this is just one of the failures, while composer gives you a full list of constraint conflicts.

**Comment by NVasse** [comment]
It's actually happening on only one of my projects so I guess the problem is on my side even though I don't know why ^^

Sorry for the trouble !
