### ISSUE TITLE
Strange fatal error in PHP 7.1 due to void return hint

### ISSUE THREAD

**Issue by tfrommen** [doctrine/instantiator#32]
Hi there,

in the last week, we (that is @inpsyde) encountered strange fatal errors when running any project depending on Instantiator, for example, on Travis CI, with **PHP 7.1**. Strange, because we can't really explain what's going on there.

> Fatal error: A void function must not return a value in /home/travis/build/inpsyde/Wonolog/vendor/doctrine/instantiator/src/Doctrine/Instantiator/Instantiator.php on line 149

You can see the fatal error [here](https://travis-ci.org/inpsyde/Wonolog/jobs/258278524), with the source (v1.1.0) being [here](https://github.com/doctrine/instantiator/blob/1.1.0/src/Doctrine/Instantiator/Instantiator.php#L148-L167).

It's obvious that there is no `return` in that method, so I believe it's actually PHP that is wrong in this regard...?

Cheers,
Thorsten

**Comment by Majkl578** [comment]
I can reproduce this locally on 7.1.7 and 7.2.0beta1, without opcache or xdebug loaded (with `-n` switch). No idea what's going on though, commented out the body of that method and it was still throwing fatal error for it... Will need further debugging, but looks like a PHP issue for sure.

**Comment by tfrommen** [comment]
Closing, as both the culprit has been found and a fix has been mentioned in https://github.com/sebastianbergmann/phpunit/issues/2746.
