### ISSUE TITLE
PHP 7.1 in composer

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [doctrine/instantiator#34]
Hello in your latest release (1.1.0 at time of writing) you suddenly  require php 7.1 in your composer.json.
I think for the most people this version is to new and I also wonder if your code uses 7.1 features already?
If not can you change this to the minimum version required (php 7.0)?

**Comment by Ocramius** [comment]
Please see https://github.com/doctrine/instantiator/issues/33 and http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

Closing as `duplicate`
