### ISSUE TITLE
doctrine/instantiator 1.0.1 requires php ~5.3 -> your PHP version (7.1.8) does not satisfy that 

### ISSUE THREAD

**Issue by shakaran** [doctrine/instantiator#35]
$ composer req doctrineorm
Using version ^1.0 for symfony/orm-pack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/instantiator 1.0.1 requires php ~5.3 -> your PHP version (7.1.8) does not satisfy that requirement.

**Comment by shakaran** [comment]
I partially solve this with:

`composer require doctrine doctrine/instantiator ^1.0.2 --update-with-dependencies`

**Comment by Ocramius** [comment]
https://github.com/doctrine/doctrine2/commit/0ec9e53c8d43d02c824dc4bfc8826a5e6e1d66e2#commitcomment-24234424

**Comment by shakaran** [comment]
@Ocramius thanks! It seems that soon will be resolved ;)

**Comment by Ocramius** [comment]
https://github.com/doctrine/doctrine2/releases/tag/v2.5.11
