### ISSUE TITLE
Requirement of PHP7.1 breaking other packages

### ISSUE THREAD

**Issue by elton182** [doctrine/instantiator#38]
All versions are requiring php7.1 and breaking other packages. 
Older versions should still required php7.0

**Comment by alcaeus** [comment]
Older versions still require whatever they require before. It’s also perfectly possible to get older versions when using an old PHP version. See http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

**Comment by elton182** [comment]
Perfect! I did not know that composer updates take into account the php version on my system.

**Comment by enumag** [comment]
@elton182 Not sure if it is your use-case but there is another thing you might be interested in.

In composer.json you can use [the platform option](https://getcomposer.org/doc/06-config.md#platform) to specify which PHP version should composer use when resolving dependencies. This is useful in cases like having PHP 7.1 locally but PHP 7.0 on production server. Normally when you update composer would happily install versions that need 7.1 and the resulting composer.lock would be useless on your production server. However when you set platform to 7.0 composer will not use such versions even if you're using 7.1 when running composer update.

This is in fact the only good option when you need to resolve all cascade dependencies correctly for an out-dated project.

**Comment by elton182** [comment]
Thanks @enumag, that's exactly what I did! It's the same case, I have php7.1 locally and 7.0 on production.
