### ISSUE TITLE
version 1.1.0 is breaking PHP < 7.1

### ISSUE THREAD

**Issue by lifeofguenter** [doctrine/instantiator#46]
Unfortunately version `1.1.0` included breaking changes which means it should have been tagged as `2.0.0` according to semver (https://semver.org/)

**Comment by Ocramius** [comment]
No, dependency updates are allowed, plus you should really already be on 7.2.

See http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html, where we explained this in detail.

See also https://github.com/semver/semver/blob/df7bd79bda7d7fe6da20d0724fe0111678cbaa8f/semver.md#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api about the bit of SemVer that specifically clarifies on this.

Besides that, if you run `composer update` on a system that resembles your production one you won't have any problems.

On my end, you can expect regular dependency major and minor version bumps in minor releases.

**Comment by Ocramius** [comment]
Duplicates #30, #32, #33, #34, #38.

I strongly suggest checking the article above, as there is most likely something broken in your composer update process.

**Comment by lifeofguenter** [comment]
@Ocramius

You are right, I did not know that composer is smart enough to check the current running version when deciding which version is compatible enough.

**Comment by GrahamCampbell** [comment]
It's not about being smart as such, it just does dependency resolution, and the platform is itself a dependency, so composer can't do much else than the "right thing".
