### ISSUE TITLE
Add in the README the meaning

### ISSUE THREAD

**Issue by higimo** [doctrine/instantiator#54]
I think this library would be useful to me ever. But now, unfortunately, I do not understand what benefits this library will bring to me.

**Comment by Ocramius** [comment]
> This library provides a way of avoiding usage of constructors when instantiating PHP classes.

That's really all there is to it.

**Comment by alcaeus** [comment]
I agree with @Ocramius here, the readme explains what the library does. If you're not sure what benefits this library will bring you, you don't need to use it: there are only a handful of use-cases where you want to instantiate objects without using the constructor.

**Comment by higimo** [comment]
> use-cases where you want to instantiate objects without using the constructor

@alcaeus for example?

**Comment by malarzm** [comment]
@higimo one of the use cases is what ORM/ODM does: Instantiating an empty object (which normally would not be possible due to required ctor arguments) to populate its properties through reflection. Effectively this allows the end-user to still use `__construct` and not be limited by a library.

**Comment by higimo** [comment]
@alcaeus why can't write this in the README?

**Comment by Ocramius** [comment]
Mostly because this is very hacky behaviour that shouldn't be endorsed for a larger audience: authors of code that need this know the requirement very well, and also how to search for this library.

Examples include mocking objects, proxying libraries, ORMs, serialisers: all very advanced pieces of code.
