### ISSUE TITLE
Promoted property causing Error

### ISSUE THREAD

**Issue by garak** [doctrine/instantiator#86]
A value object, mapped as embeddable, perfectly working:
```php
<?php
class Foo {
    private ?string $bar = null;
    public function __construct(?string $bar) {
        $this->bar = $bar;
    }
}
```
But if you try to promote property:
```php
<?php
class Foo {
    public function __construct(private ?string $bar = null) {
    }
}
```
It fails with `Error: Typed property Foo::$bar must not be accessed before initialization` as soon as you try to access property.

Property is not mapped.

Edit: tried to downgrade to Doctrine 2.8 to check if could be a problem with 2.9: no changes.

**Comment by derrabus** [comment]
Can we close this issue? I don't think it's actionable for us.
